### ISSUE TITLE
[llbm] miBench dataset has optnone function attribute set

### ISSUE THREAD

**Issue by yqtian-se** [facebookresearch/CompilerGym#505] opened 2021-12-08 17:56 UTC
## 🐛 Bug

I am not sure whether it is a bug, or perhaps it is due to the dataset?

I run the e-greedy algorithm https://github.com/facebookresearch/CompilerGym/blob/development/leaderboard/llvm_instcount/e_greedy/e_greedy.py on  mibench. The results seems does not make sense at all: all rewards are 0 in terms of instruction count.

I don't think it is due the implementation of e_greedy.py. Actually I wrote one version of greedy algorithm and it has the same results.

Why this happen? any problem in the benchmark? should we add some notes about this in the website? 

## To Reproduce

1. `python e_greedy.py --n=1 --epsilon=0 --test_dataset=mibench-v0 --leaderboard_results=greedy_mibench.csv`

[greedy_mibench.csv](https://github.com/facebookresearch/CompilerGym/files/7677924/greedy_mibench.csv)

## Environment

Please fill in this checklist:

- CompilerGym: 0.2.1
- How you installed CompilerGym (conda, pip, source): pip
- OS: Ubuntu 18.04
- Python version: 3.6.9
- Build command you used (if compiling from source):
- GCC/clang version (if compiling from source):
- Bazel version (if compiling from source):
- Versions of any other relevant libraries:

**Comment by ChrisCummins** [comment] 2021-12-09 17:59
Hi @yqtianust, thanks for the report!

This is indeed a bug. All mibench programs have the same size when optimized by -Oz. Test script:

```py
import compiler_gym
env = compiler_gym.make("llvm-v0")
for benchmark in env.datasets["mibench-v0"].benchmarks():
    env.reset(benchmark=benchmark)
    print(benchmark, env.observation.IrInstructionCount(), env.observation.IrInstructionCountOz())
```

Produces output:

```
benchmark://mibench-v0/bitcount-1 124 124
benchmark://mibench-v0/bitcount-2 131 131
benchmark://mibench-v0/dijkstra 121 121
benchmark://mibench-v0/fft-1 131 131
benchmark://mibench-v0/fft-2 362 362
benchmark://mibench-v0/ghostscript 194 194
benchmark://mibench-v0/gsm-1 218 218
benchmark://mibench-v0/gsm-2 222 222
benchmark://mibench-v0/jpeg-c-1 177 177
benchmark://mibench-v0/jpeg-c-2 347 347
benchmark://mibench-v0/jpeg-c-3 325 325
benchmark://mibench-v0/jpeg-c 645 645
benchmark://mibench-v0/lame-newmdct-1 569 569
benchmark://mibench-v0/lame-newmdct-2 189 189
benchmark://mibench-v0/lame-psymodel 1563 1562
benchmark://mibench-v0/lame-quantize-1 161 161
benchmark://mibench-v0/lame-quantize-2 129 129
benchmark://mibench-v0/lame-takehiro-1 386 388
benchmark://mibench-v0/lame-takehiro-2 162 162
benchmark://mibench-v0/mad-1 391 391
benchmark://mibench-v0/mad-2 243 243
benchmark://mibench-v0/pgp-d 149 149
benchmark://mibench-v0/pgp-e-1 149 149
benchmark://mibench-v0/pgp-e-2 158 158
benchmark://mibench-v0/pgp-e-3 171 171
benchmark://mibench-v0/qsort1 114 114
benchmark://mibench-v0/rsynth-1 224 224
benchmark://mibench-v0/rsynth-2 155 155
benchmark://mibench-v0/susan-e-1 215 215
benchmark://mibench-v0/susan-e-2 1629 1629
benchmark://mibench-v0/susan-s 231 231
benchmark://mibench-v0/tiff2rgba 340 340
benchmark://mibench-v0/tiffdither-1 331 331
benchmark://mibench-v0/tiffdither-2 331 331
benchmark://mibench-v0/tiffdither-3 244 244
benchmark://mibench-v0/tiffmedian-1 229 229
benchmark://mibench-v0/tiffmedian-2 158 158
benchmark://mibench-v0/tiffmedian-3 220 220
benchmark://mibench-v0/tiffmedian-4 251 251
benchmark://mibench-v0/tiffmedian-5 181 181
```

The problem is that mibench bitcodes have been prepared without the right flags, causing the `optnone` function attribute on all bitcodes:

```llvm
; Function Attrs: noinline nounwind optnone ssp uwtable
define void @astex_codelet__6(%struct.colorbox* %0, %struct.colorbox* %1, i32 %2, %struct.colorbox** %3, i32* %4) #0 {
```

For more context, see [here](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/llvm_benchmark.py#L150-L169). I will fix this before the next release, either by recompiling the bitcodes or removing the dataset.

Good catch!

Cheers,
Chris

**Comment by yqtian-se** [comment] 2021-12-10 01:28
Thanks for the detailed feedback. Good to know it is a bug.

**Comment by ChrisCummins** [comment] 2021-12-10 02:29
Hi @yqtianust,

I have made a new `mibench-v1` dataset which contains the same files with the `optnone` attribute stripped so that the compiler can improve them:

```py
In [6]: import compiler_gym
   ...: env = compiler_gym.make("llvm-v0")
   ...: for benchmark in env.datasets["mibench-v1"].benchmarks():
   ...:     env.reset(benchmark=benchmark)
   ...:     print(benchmark, env.observation.IrInstructionCount(), env.observation.IrInstructionCountOz())
...
benchmark://mibench-v1/bitcount-1 124 45
benchmark://mibench-v1/bitcount-2 131 49
benchmark://mibench-v1/dijkstra 121 46
benchmark://mibench-v1/fft-1 131 47
benchmark://mibench-v1/fft-2 362 129
benchmark://mibench-v1/ghostscript 194 54
benchmark://mibench-v1/gsm-1 218 95
benchmark://mibench-v1/gsm-2 222 85
benchmark://mibench-v1/jpeg-c-1 177 70
benchmark://mibench-v1/jpeg-c-2 347 139
benchmark://mibench-v1/jpeg-c-3 325 132
benchmark://mibench-v1/jpeg-c 645 200
benchmark://mibench-v1/lame-newmdct-1 569 313
benchmark://mibench-v1/lame-newmdct-2 189 80
benchmark://mibench-v1/lame-psymodel 1563 507
benchmark://mibench-v1/lame-quantize-1 161 61
benchmark://mibench-v1/lame-quantize-2 129 50
benchmark://mibench-v1/lame-takehiro-1 386 145
benchmark://mibench-v1/lame-takehiro-2 162 60
benchmark://mibench-v1/mad-1 391 297
benchmark://mibench-v1/mad-2 243 97
benchmark://mibench-v1/pgp-d 149 60
benchmark://mibench-v1/pgp-e-1 149 60
benchmark://mibench-v1/pgp-e-2 158 58
benchmark://mibench-v1/pgp-e-3 171 63
benchmark://mibench-v1/qsort1 114 47
benchmark://mibench-v1/rsynth-1 224 65
benchmark://mibench-v1/rsynth-2 155 44
benchmark://mibench-v1/susan-e-1 215 88
benchmark://mibench-v1/susan-e-2 1629 610
benchmark://mibench-v1/susan-s 231 87
benchmark://mibench-v1/tiff2rgba 340 165
benchmark://mibench-v1/tiffdither-1 331 145
benchmark://mibench-v1/tiffdither-2 331 145
benchmark://mibench-v1/tiffdither-3 244 104
benchmark://mibench-v1/tiffmedian-1 229 72
benchmark://mibench-v1/tiffmedian-2 158 61
benchmark://mibench-v1/tiffmedian-3 220 99
benchmark://mibench-v1/tiffmedian-4 251 90
benchmark://mibench-v1/tiffmedian-5 181 77
```

The dataset will be available in the next CompilerGym release, or as soon as #511 is merged if you are building from the development branch.

Cheers,
Chris

**Comment by yqtian-se** [comment] 2021-12-10 03:04
Thanks. I will have a try. Do I need to manually remove the cache of the old version mibench?

**Comment by ChrisCummins** [comment] 2021-12-10 03:30
No, just update references from mibench-v0 to mibench-v1.

Cheers,
Chris

**Closed as completed** 2021-12-10 15:54 UTC
Labels: Bug, Datasets
