### ISSUE TITLE
Failed to create connection to compiler_gym-llvm-service after 0.5 seconds (5 attempts made)

### ISSUE THREAD

**Issue by sunch20** [facebookresearch/CompilerGym#787] opened 2023-03-07 02:15 UTC
## 🐛 Bug

This is my first time to use Compilergym. When I write command "env = gym.make("llvm-autophase-ic-v0")" , it reports error : "compiler_gym.errors.service_errors.ServiceError: Failed to create connection to compiler_gym-llvm-service after 0.5 seconds (5 attempts made) Last error (ServiceError): Service terminated with returncode: 127"
## To Reproduce

1.use "pip install -U compiler_gym" to install this library on Ubuntu 22.04.
2.entry "python3" environment and "import gym"、"import compiler_gym"
3.after the above steps, write command "env = gym.make("llvm-autophase-ic-v0")"

"compiler_gym.errors.service_errors.ServiceError: Failed to create connection to compiler_gym-llvm-service after 0.5 seconds (5 attempts made) 
Last error (ServiceError): Service terminated with returncode: 127"

## Expected behavior

How can I solve this bug?

## Environment

Please fill in this checklist:

- CompilerGym:
- How you installed CompilerGym (pip, source): pip install
- OS: Ubuntu 22.04
- Python version: 3.10.6
- Build command you used (if compiling from source):
- GCC/clang version (if compiling from source):
- Versions of any other relevant libraries:

You may use the
[environment collection script](https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ChrisCummins** [comment] 2023-03-14 07:40
Hi @sunch20, hmm, it seems like something is failing behind the scenes, possibly an issue with the environment. Could you please share the output of the following script? It should provide more verbose errors:

```py
import os
import compiler_gym

os.environ["COMPILER_GYM_DEBUG"] = "3"
env = compiler_gym.make("llvm-v0")
env.close()
```

Cheers,
Chris

**Comment by ChrisCummins** [comment] 2023-03-14 07:42
FWIW, I can't reproduce the error on any system I have access to. You could use [Google colab](https://colab.research.google.com/drive/1fhPg3JGGJhcuna3jRL_GoNEZensiMOGZ?usp=sharing) to run CompilerGym if you just want to play around with it.

Cheers,
Chris

**Comment by sunch20** [comment] 2023-03-14 07:59
> Hi @sunch20, hmm, it seems like something is failing behind the scenes, possibly an issue with the environment. Could you please share the output of the following script? It should provide more verbose errors:
> 
> ```python
> import os
> import compiler_gym
> 
> os.environ["COMPILER_GYM_DEBUG"] = "3"
> env = compiler_gym.make("llvm-v0")
> env.close()
> ```
> 
> Cheers, Chris

hello, I executed the above commands, here is the output：
"""
sunch@sunch-virtual-machine:~/Desktop$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
'>>> import os
'>>> import compiler_gym
'>>> os.environ["COMPILER_GYM_DEBUG"] = "3"
'>>> env = compiler_gym.make("llvm-v0")
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 1)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 2)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 3)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 4)
./compiler_gym-llvm-service: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ServiceError Service terminated with returncode: 127 (attempt 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/util/registration.py", line 16, in make
    return gym.make(id, **kwargs)
  File "/home/sunch/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/sunch/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/home/sunch/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 93, in __init__
    super().__init__(
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/service/client_service_compiler_env.py", line 207, in __init__
    self.service = service_connection or CompilerGymServiceConnection(
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/service/connection.py", line 646, in __init__
    self._establish_connection()
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/service/connection.py", line 657, in _establish_connection
    self.connection = self._create_connection(self.endpoint, self.opts)
  File "/home/sunch/.local/lib/python3.10/site-packages/compiler_gym/service/connection.py", line 718, in _create_connection
    raise exception_class(
compiler_gym.errors.service_errors.ServiceError: Failed to create connection to compiler_gym-llvm-service after 0.5 seconds (5 attempts made).
Last error (ServiceError): Service terminated with returncode: 127
'>>> 
"""

**Comment by ChrisCummins** [comment] 2023-03-14 09:55
Thanks for the extra info @sunch20! The problem is the missing `libtinfo5` library. Can you try running this:

```
sudo apt install libtinfo5
```

and then repeating the above script?

Cheers,
Chris

**Comment by sunch20** [comment] 2023-03-17 03:00
Thank you very much for your help. According to what you said, the problem has been resolved.


在 2023年3月14日 17:56，Chris ***@***.***> 写道：


Thanks for the extra info @sunch20! The problem is the missing libtinfo5 library. Can you try running this:
sudo apt install libtinfo5
and then repeating the above script?
Cheers,
 Chris

**Comment by ChrisCummins** [comment] 2023-03-21 00:17
That's great to hear. Closing this, but feel free to file and new issues or questions!

Cheers,
Chris

**Closed as completed by ChrisCummins** 2023-03-21 00:17 UTC
Labels: Bug
